[[language]]
name = "svelte"
auto-format = true
language-servers = [ "svelteserver", "tailwindcss-ls" ]

[[language]]
name ="glsl"
auto-format = true
language-servers = ['glsl_analyzer']

[language-server.pyrefly]
command = "pyrefly"
args = [ "lsp" ]

[[language]]
name = "python"
language-servers = [ "pyrefly" ]
